#!/bin/bash
##SBATCH -n 1
##SBATCH -N 1
#SBATCH -p gpu
#SBATCH -t 3-00:00
#SBATCH --mem=10000
#SBATCH --gres=gpu:1
#SBATCH --job-name=continual_learning
#SBATCH -o logs/train_eval_%j.out
#SBATCH -e logs/train_eval_%j.err
export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128
source activate /n/home05/alanhsu/.conda/envs/continualLearning
#python /n/home05/alanhsu/workspace/research/continual_learning/main_batch.py --config /n/home05/alanhsu/workspace/research/continual_learning/configs/cifar10_train_ideal_model.yaml

#cp -r /n/home05/alanhsu/workspace/research/continual_learning/models/cifar10_split/random/1 /n/home05/alanhsu/workspace/research/continual_learning/models/cifar10_split/ideal_model

python /n/home05/alanhsu/workspace/research/continual_learning/main_batch.py --config /n/home05/alanhsu/workspace/research/continual_learning/configs/random/config_cifar10_grad_eval.yaml
#python /n/home05/alanhsu/workspace/research/continual_learning/main_batch.py --config /n/home05/alanhsu/workspace/research/continual_learning/configs/random/config_cifar10_train.yaml

#python /n/home05/alanhsu/workspace/research/continual_learning/save_similarity_block_v2.py --config /n/home05/alanhsu/workspace/research/continual_learning/configs/grad_eval/cifar10_random.yaml
