# WandB stuff, change according to user
use_wandb: True
wandb_project_name: continuallearning
wandb_profile: alanhsu


# Memory set hyperparameters
memory_set_manager: random
use_memory_set: True
p: 0.1
#num_samples: 10

# for graident evaluating
p_arr: [0.001, 0.005, 0.01, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
#num_samples: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
num_samples: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

#training
#p_arr: [1]
#num_samples: [1] # if training, use only 1 sample

# Continual learning hyperparameters
learning_manager: mnist_split

# Training hyperparameters
lr: 0.001
batch_size: 256
random_seed: 0xC0FFEE
epochs: 30

# Model arch 
model:
 type: mlp 
 params: 
   sizes: [784, 100, 10] 
   acts: [relu]

#Example CNN
# model: 
#   type: cnn
#   params: 
#     in_channels: 3 
#     out_channels: 10
#     l1_out_channels: 32
#     l2_out_channels: 32
#     l3_out_channels: 64
#     l4_out_channels: 64


model_save_dir: models/mnist_split #/1/
#model_load_dir: models/mnist_split