# WandB stuff, change according to user
use_wandb: False
wandb_project_name: continuallearning
wandb_profile: alanhsu


# Memory set hyperparameters
memory_set_manager: random
use_memory_set: True
grad_type: None
p: dummar_var
use_random_img: False
#num_samples: 1
num_ideal_models: None

p_arr: [0.001]
num_samples: [10]

#debugging 
train_debug: False

# Continual learning hyperparameters
#learning_manager: mnist_split
learning_manager: cifar10_split

# Training hyperparameters
lr: 0.001
batch_size: 256
random_seed: 0xC0FFEE

#epochs: 30
#CHANGED
# epochs: 50
epochs: 2

#Example CNN
model: 
  type: cnn
  params: 
    in_channels: 3 
    out_channels: 10
    l1_out_channels: 32
    l2_out_channels: 32
    l3_out_channels: 64
    l4_out_channels: 64


#CHANGED
# model_save_dir: models/cifar10_split
model_save_dir: models/parallel_cifar10_split